### ISSUE TITLE
最新版本的 swow 要使用 "hyperf/engine-swow:^1.2"

### ISSUE THREAD

**Issue by limingxinleo** [SerendipitySwow/Serendipity-job#10]

**Comment by limingxinleo** [comment]
https://github.com/swow/swow/releases/tag/v0.1.0-nightly20210910

**Comment by codingheping** [comment]
你1.2还是beta版本呢

**Comment by limingxinleo** [comment]
是的，我先跑跑。国庆前会发release



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: codingheping ***@***.***&gt;
发送时间: 2021年9月24日 10:37
收件人: SerendipitySwow/Serendipity-job ***@***.***&gt;
抄送: 李铭昕 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[SerendipitySwow/Serendipity-job] 最新版本的 swow 要使用 "hyperf/engine-swow:^1.2" (#10)





 
你1.2还是beta版本呢
